# Desafío - Manipulación y transformación de datos
(Parte I)

En este desafío validaremos nuestros conocimientos de uso de DataFrames, manipulando y
transformando datos de ellos. Para lograrlo, necesitarás aplicar lo que has aprendido
durante esa sesión.

Lee todo el documento antes de comenzar el desarrollo individual, para asegurarte de tener
el máximo de puntaje y enfocar bien los esfuerzos.

Tiempo asociado: 2 horas cronológicas

**Descripción**

#  1. Para desarrollar este desafío necesitarás los siguientes archivos:
*   incidents.pkl
*   officers.pkl
*   subjects.pkl

a. Carga los datos y crea un DataFrame con cada uno de ellos.

b. Genera una tabla que contenga la unión de las 3 tablas. hint: utiliza sufijos para para las
columnas que se llaman igual usando el parámetro suffixes de pd.merge().

c. Verifica si hay filas duplicadas; si es así, elimínalas.

d. ¿Cuántos sujetos de género F hay en el DataFrame resultante? hint: usa el método
.value_counts() sobre la columna.

e. ¿En cuántos números de caso hay por lo menos una sospechosa que sea mujer? hint:
utiliza el método unique() para obtener los valores únicos de una columna específica de
un DataFrame luego de filtrar.

f. Genera una tabla pivote que muestre en las filas el género del oficial y en las columnas el
género del subject. ¿Cómo interpretas los valores que muestra esta vista?

## a. Carga los datos y crea un DataFrame con cada uno de ellos.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pickle
import pandas as pd
import numpy as np
df_officers = pd.read_pickle(r'/content/drive/MyDrive/Colab Notebooks/Desafío - Manipulación y transformación de datos (Parte I)/officers.pkl')
df_incidents = pd.read_pickle(r'/content/drive/MyDrive/Colab Notebooks/Desafío - Manipulación y transformación de datos (Parte I)/incidents.pkl')
df_subjects = pd.read_pickle (r'/content/drive/MyDrive/Colab Notebooks/Desafío - Manipulación y transformación de datos (Parte I)/subjects.pkl')

### df_officers

In [ ]:
df_officers.head()

  case_number race gender  last_name first_name         full_name
0      44523A    L      M     Patino    Michael   Patino, Michael
1      44523A    W      M  Fillingim      Brian  Fillingim, Brian
2     121982X    L      M    Padilla    Gilbert  Padilla, Gilbert
3     605484T    W      M     Poston      Jerry     Poston, Jerry
4     384832T    B      M      Mondy    Michael    Mondy, Michael

### df_incidents

In [ ]:
df_incidents.head()

,case_number,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,attorney_general_forms_url,summary_url,summary_text,latitude,longitude
0,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
1,121982X,2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN
2,605484T,2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN
3,384832T,2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN
4,244659R,2006-04-03,6512 South Loop 12,Injured,Hands,"Watkins, Caleb B/M",1,"Armstrong, Michael W/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, April 3, 2006, at approximately 11:...",NaN,NaN

### df_subjects

In [ ]:
df_subjects.head(20)

    case_number race gender    last_name first_name           full_name
0        44523A    L      M        Curry      James        Curry, James
1       121982X    L      M       Chavez    Gabriel     Chavez, Gabriel
2       605484T    L      M      Salinas       Nick       Salinas, Nick
3       384832T    B      M        Smith      James        Smith, James
4       384832T    B      M         Dews    Antonio       Dews, Antonio
5       384832T    B      M     Spearman     Damion    Spearman, Damion
6       244659R    B      M      Watkins      Caleb      Watkins, Caleb
7       363184P    L      M       Garcia      David       Garcia, David
8       559487M    B      M       Vernon       Tony        Vernon, Tony
9       862009M    L      M      Fuentes  Francisco  Fuentes, Francisco
10       60045A    B      M      Johnson    Tyrique    Johnson, Tyrique
11  236112-2014    W      M      Cupples  Jimmy Jr.  Cupples, Jimmy Jr.
12       27878Z    B      M        Glenn   Randolph     Glenn, Randolph
13      963516P    B      M  Keliam Rudd       None         Keliam Rudd
14      373521W    L      M      Vasquez      Angel      Vasquez, Angel
15      194631A    L      M      Unknown       None             Unknown
16  134472-2015    W      M     Boulware      James     Boulware, James
17      871610R    B      M      Linwood     Robert     Linwood, Robert
18      118251R    L      M       Tamayo  Alejandro   Tamayo, Alejandro
19      989995N    B      M     Williams      Corey     Williams, Corey

## b. Genera una tabla que contenga la unión de las 3 tablas. hint: utiliza sufijos para para las
Columnas que se llaman igual usando el parámetro suffixes de pd.merge().

In [ ]:
#Se fusionan las tablas officers e incidents:

merged_df = pd.merge(df_officers, df_incidents, on ='case_number', how = 'inner', suffixes=('_incidents', '_officer'))

In [ ]:
merged_df.head() #La fusion de tablas df_officers, df_incidents es llamada merged_df

,case_number,race,gender,last_name,first_name,full_name,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,attorney_general_forms_url,summary_url,summary_text,latitude,longitude
0,44523A,L,M,Patino,Michael,"Patino, Michael",2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
1,44523A,W,M,Fillingim,Brian,"Fillingim, Brian",2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
2,121982X,L,M,Padilla,Gilbert,"Padilla, Gilbert",2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN
3,605484T,W,M,Poston,Jerry,"Poston, Jerry",2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN
4,384832T,B,M,Mondy,Michael,"Mondy, Michael",2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN

In [ ]:
#Fusionamos la tercer tabla subjects.

final_df = pd.merge(merged_df, df_subjects, on ='case_number', how = 'inner', suffixes=('', '_subject'))

final_df.head() #La tabla final queda con el nombre final_df

,case_number,race,gender,last_name,first_name,full_name,date,location,subject_statuses,subject_weapon,...,attorney_general_forms_url,summary_url,summary_text,latitude,longitude,race_subject,gender_subject,last_name_subject,first_name_subject,full_name_subject
0,44523A,L,M,Patino,Michael,"Patino, Michael",2013-02-23,3000 Chihuahua Street,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN,L,M,Curry,James,"Curry, James"
1,44523A,W,M,Fillingim,Brian,"Fillingim, Brian",2013-02-23,3000 Chihuahua Street,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN,L,M,Curry,James,"Curry, James"
2,121982X,L,M,Padilla,Gilbert,"Padilla, Gilbert",2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN,L,M,Chavez,Gabriel,"Chavez, Gabriel"
3,605484T,W,M,Poston,Jerry,"Poston, Jerry",2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN,L,M,Salinas,Nick,"Salinas, Nick"
4,384832T,B,M,Mondy,Michael,"Mondy, Michael",2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN,B,M,Smith,James,"Smith, James"

## c. Verifica si hay filas duplicadas; si es así, elimínalas

In [ ]:
#Verificamos cuatas filas y columnas tiene la tabla.
print(final_df.shape)

(377, 25)

In [ ]:
#Eliminamos tablas duplicadas
df = final_df.drop_duplicates()
#Revisamos si hubo cambios, se mantiene igual.
print(df.shape)
df.head() #Dejamos el nombre de df para mas facilidad.

(377, 25)

,case_number,race,gender,last_name,first_name,full_name,date,location,subject_statuses,subject_weapon,...,attorney_general_forms_url,summary_url,summary_text,latitude,longitude,race_subject,gender_subject,last_name_subject,first_name_subject,full_name_subject
0,44523A,L,M,Patino,Michael,"Patino, Michael",2013-02-23,3000 Chihuahua Street,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN,L,M,Curry,James,"Curry, James"
1,44523A,W,M,Fillingim,Brian,"Fillingim, Brian",2013-02-23,3000 Chihuahua Street,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN,L,M,Curry,James,"Curry, James"
2,121982X,L,M,Padilla,Gilbert,"Padilla, Gilbert",2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN,L,M,Chavez,Gabriel,"Chavez, Gabriel"
3,605484T,W,M,Poston,Jerry,"Poston, Jerry",2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN,L,M,Salinas,Nick,"Salinas, Nick"
4,384832T,B,M,Mondy,Michael,"Mondy, Michael",2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN,B,M,Smith,James,"Smith, James"

## d. ¿Cuántos sujetos de género F hay en el DataFrame resultante? hint: usa el método .value_counts() sobre la columna.

In [ ]:
count_female = df['gender'].value_counts().get('F',0)
print(count_female) #Contamos cuantas filas tienen F en Gender.

20

In [ ]:
df_females = df[df['gender'] == 'F']
df_females.head(25) #Aqui podemos confirmar las 20 filas que nos mostro el count.

,case_number,race,gender,last_name,first_name,full_name,date,location,subject_statuses,subject_weapon,...,attorney_general_forms_url,summary_url,summary_text,latitude,longitude,race_subject,gender_subject,last_name_subject,first_name_subject,full_name_subject
18,373521W,L,F,Rebecca Barrios,None,Rebecca Barrios,2009-12-20,14500 Dallas North Parkway,Injured,Hands,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, December 20, 2009, at approximately...",32.94500,-96.822619,L,M,Vasquez,Angel,"Vasquez, Angel"
26,134472-2015,L,F,Arispi,Cynthia,"Arispi, Cynthia",2015-06-13,1400 South Lamar Street,Deceased,Rifle,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On June 13, 2015, at approximately 12:20 a.m.,...",32.76730,-96.795013,W,M,Boulware,James,"Boulware, James"
27,134472-2015,L,F,Ochoa,Michelle,"Ochoa, Michelle",2015-06-13,1400 South Lamar Street,Deceased,Rifle,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On June 13, 2015, at approximately 12:20 a.m.,...",32.76730,-96.795013,W,M,Boulware,James,"Boulware, James"
42,989995N,W,F,Rumancik,Megan,"Rumancik, Megan",2004-12-24,4100 Garrison Street,Injured,Hands,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Friday, December 24, 2004, at approximately...",32.70298,-96.786995,B,M,Williams,Corey,"Williams, Corey"
48,309130W,B,F,Ferguson,Kesha,"Ferguson, Kesha",2009-10-17,3902 Frank Street,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, October 17, 2009, at approximatel...",32.77188,-96.749393,B,M,Wilson,Alerick,"Wilson, Alerick"
52,165748Y,W,F,Silvia,Katherine,"Silvia, Katherine",2011-06-24,7152 Fair Oaks Avenue,Shoot and Miss,Vehicle,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Friday, June 24, 2011, at approximately 8:5...",32.87317,-96.757780,B,M,Unknown,None,Unknown
82,311475A,W,F,Wilburn,Amy,"Wilburn, Amy",2013-12-09,9524 Military Parkway,Injured,Unarmed,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, December 9, 2013, at approximately ...",32.76831,-96.657518,B,M,Walker,Kelvion,"Walker, Kelvion"
104,79223B,W,F,Moore,Jacqueline,"Moore, Jacqueline",2014-04-04,1221 S. Lamar Street,Deceased,Knife,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Friday, April 4, 2014, at approximately 9:3...",32.76867,-96.796936,W,M,Bullard,Codi,"Bullard, Codi"
128,8025N,B,F,Huel,Tammy,"Huel, Tammy",2004-01-03,6950 Marvin D. Love Freeway,Deceased,Knife,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, January 3, 2004, at approximately...",32.66360,-96.867936,B,F,Kemp,Diane,"Kemp, Diane"
154,199250-2015,W,F,Rice,Rachel,"Rice, Rachel",2015-08-27,3610 Penelope Street,Deceased,Pellet Gun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On August 27, 2015, officers responded to a ro...",32.77078,-96.753149,B,M,Davis,Bertrand,"Davis, Bertrand"
169,161783A,L,F,Salazar,Samantha,"Salazar, Samantha",2013-06-26,2310 Martin Luther King Jr. Blvd,Injured,Knife,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Wednesday, June 26, 2013, at approximately ...",32.76472,-96.773437,B,M,Anderson,Edward Jr.,"Anderson, Edward Jr."
199,1066R,None,F,Tahbone,Jacqueline,"Tahbone, Jacqueline",2006-01-01,5423 Peterson Lane #259,Injured,Knife,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, January 1, 2006 at about 5:00 A.M, ...",32.93060,-96.814373,L,M,Robles,Juan,"Robles, Juan"
230,221021N,B,F,Richardson,Paulette,"Richardson, Paulette",2004-03-27,4515 Village Fair Drive,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, March 27, 2004, at 2:30 P.M., a s...",32.69084,-96.829549,B,M,Hicks,Lavell,"Hicks, Lavell"
231,221021N,B,F,Lewis,Sharlet,"Lewis, Sharlet",2004-03-27,4515 Village Fair Drive,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, March 27, 2004, at 2:30 P.M., a s...",32.69084,-96.829549,B,M,Hicks,Lavell,"Hicks, Lavell"
328,337026Y,W,F,Magiera,Stormy,"Magiera, Stormy",2011-12-28,11700 Audelia Road,Shoot and Miss,Unarmed,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Wednesday, December 28, 2011, at approximat...",32.90855,-96.717640,B,M,Dixon,Derrick,"Dixon, Derrick"
333,129379Z,B,F,Edwards,Marilyn,"Edwards, Marilyn",2012-05-26,2000 Campfire Circle,Shoot and Miss,Vehicle,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2012, at approximately 8:...",32.68279,-96.855363,L,M,Unknown,None,Unknown
334,129379Z,B,F,Edwards,Marilyn,"Edwards, Marilyn",2012-05-26,2000 Campfire Circle,Shoot and Miss,Vehicle,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2012, at approximately 8:...",32.68279,-96.855363,L,F,Unknown,None,Unknown
342,403476M,W,F,Yanez,Tami,"Yanez, Tami",2003-06-01,4220 Independence Drive,Deceased,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, June 1, 2003, at approximately 1:23...",32.66099,-96.889139,B,M,West,Samuel III,"West, Samuel III"
349,213806V,B,F,Jenkins,Jocelyn,"Jenkins, Jocelyn",2008-07-09,1613 Monte Carlo Street,Deceased,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Wednesday, July 9, 2008, at approximately 9...",32.70640,-96.846410,L,M,Robles,Rodrigo,"Robles, Rodrigo"
351,200830-2014,W,F,Herczeg,Michelle,"Herczeg, Michelle",2014-08-20,7921 L.B.J. Freeway,Injured,Handgun,...,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Wednesday, August 20, 2014, at approximatel...",32.92484,-96.770077,W,M,Groessel,Terence,"Groessel, Terence"

## e. ¿En cuántos números de caso hay por lo menos una sospechosa que sea mujer? hint: utiliza el método unique() para obtener los valores únicos de una columna específica de un DataFrame luego de filtrar.

In [ ]:
#Hacemos la variable is_female y filtramos por la columna gender, en el df.
#Donde todo sea F, para que nos muestre los case_numbers
is_female = df[df['gender'] == 'F']['case_number']
is_female.nunique() #.nunique() muestra el numeros de valores unicos.

17

In [ ]:
is_female.unique() #unique() muestra la lista de valores unicos.

array(['373521W', '134472-2015', '989995N', '309130W', '165748Y',
       '311475A', '79223B', '8025N', '199250-2015', '161783A', '1066R',
       '221021N', '337026Y', '129379Z', '403476M', '213806V',
       '200830-2014'], dtype=object)

In [ ]:
repeated = df[df["gender"] == "F"]["case_number"].value_counts()
print(repeated) #Para complementar la informacion, mostramos cuales son repetidos y cuales no.

case_number
129379Z        2
221021N        2
134472-2015    2
373521W        1
161783A        1
213806V        1
403476M        1
337026Y        1
1066R          1
199250-2015    1
8025N          1
79223B         1
311475A        1
165748Y        1
309130W        1
989995N        1
200830-2014    1
Name: count, dtype: int64

## f. Genera una tabla pivote que muestre en las filas el género del oficial y en las columnas el género del subject. ¿Cómo interpretas los valores que muestra esta vista?

In [ ]:
tabla_pivote = pd.pivot_table(df, index = 'gender', columns = 'gender_subject', aggfunc = 'size',fill_value= 0)
tabla_pivote

gender_subject  F    M
gender
F               2   18
M               7  350

Viendo el resultado, nos ayuda a saber si existe un patron clave en la asignacion de sospechosos segun el genero.

# 2. Para continuar con el desarrollo de este desafío, necesitarás el archivos
Cleaned_DS_Jobs.csv

## a. Carga los datos y crea un DataFrame con ellos.

2. Para continuar con el desarrollo de este desafío, necesitarás el archivos
Cleaned_DS_Jobs.csv
a. Carga los datos y crea un DataFrame con ellos.

b. Utiliza la siguiente lista de valores que serán considerados como nulos:
["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"]
(hint: utiliza el método replace para reemplazar los valores indicados por np.nan)

c. Elimina todas las filas con datos faltantes. (hint: utiliza el método .dropna())

d. A partir de la columna “Salary Estimate”, genera dos columnas: Salario Estimado Mínimo
y Máximo. (hint: Utiliza el método apply sobre la columna.)

e. Realiza la recodificación de la columna Size con los valores de la siguiente tabla: (hint:
utilice reemplazo con diccionario usando el método replace sobre la columna.)



f. Finalmente, genera una tabla pivote que muestre la media del salario estimado mínimo y
la media del salario estimado máximo por tamaño de empresa. (hint: utiliza
pd.pivot_table para generar la vista adecuada con las columnas generadas.)

In [ ]:
import pandas as pd
import numpy as np
cleaned_ds = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Desafío - Manipulación y transformación de datos (Parte I)/Cleaned_DS_Jobs.csv')

In [ ]:
cleaned_ds.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

## b. Utiliza la siguiente lista de valores que serán considerados como nulos:

In [ ]:
valores_nulos = ["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"]

In [ ]:
cleaned_ds.replace(valores_nulos, np.nan, inplace=True)

In [ ]:
cleaned_ds.head()
print(cleaned_ds.shape)

(80, 27)

## c. Elimina todas las filas con datos faltantes. (hint: utiliza el método .dropna())

In [ ]:
cleaned_ds.dropna(inplace = True)
df = cleaned_ds
df #Asignamos la tabla limpia como df, para mayor facilidad.

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27.0,0,0,0,0,1,0,0,data scientist,senior
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,95.0,0,0,0,0,0,0,0,data scientist,senior
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,54.0,1,1,0,0,1,1,0,data scientist,senior
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,Company - Private,Computer Hardware & Software,...,8.0,0,0,0,0,0,0,0,data scientist,senior
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,Company - Private,Biotech & Pharmaceuticals,...,8.0,1,1,0,0,0,0,1,data scientist,senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,Senior Data Engineer,138-158,Senior Data Engineer\n\nMaster’s degree in Inf...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22.0,1,0,1,1,0,1,0,data engineer,senior
583,Senior Data Scientist,80-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,38.0,1,0,1,1,0,0,1,data scientist,senior
601,Senior Data Scientist,87-141,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52.0,1,0,1,1,0,1,1,data scientist,senior
640,Senior Data Scientist,105-167,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",51 to 200 employees,Company - Private,Advertising & Marketing,...,11.0,0,0,0,0,0,0,0,data scientist,senior
641,Sr. ML/Data Scientist - AI/NLP/Chatbot,105-167,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",5001 to 10000 employees,Company - Public,Telecommunications Services,...,24.0,1,1,0,1,1,0,0,data scientist,senior

## d. A partir de la columna “Salary Estimate”, genera dos columnas: Salario Estimado Mínimo y Máximo. (hint: Utiliza el método apply sobre la columna.)

In [ ]:
df[['Salario Estimado Mínimo', 'Salario Estimado Máximo']] = df['Salary Estimate'].apply(lambda x: pd.Series([int(x.split('-')[0].strip()), int(x.split('-')[1].strip())]))
df #Utilizamos metodo apply y lambda.

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario Estimado Mínimo,Salario Estimado Máximo
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",Medianas Empresas,Nonprofit Organization,Insurance Carriers,...,0,0,0,1,0,0,data scientist,senior,137,171
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",Medianas Empresas,Company - Private,Insurance Carriers,...,0,0,0,0,0,0,data scientist,senior,75,131
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",Microempresas,Company - Private,Internet,...,1,0,0,1,1,0,data scientist,senior,75,131
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",Pequeñas Empresas,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,0,data scientist,senior,75,131
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",Pequeñas Empresas,Company - Private,Biotech & Pharmaceuticals,...,1,0,0,0,0,1,data scientist,senior,75,131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,Senior Data Engineer,138-158,Senior Data Engineer\n\nMaster’s degree in Inf...,2.9,Affinity Solutions,"New York, NY","New York, NY",Pequeñas Grandes Empresas,Company - Private,Advertising & Marketing,...,0,1,1,0,1,0,data engineer,senior,138,158
583,Senior Data Scientist,80-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",Grandes Empresas,Company - Public,Computer Hardware & Software,...,0,1,1,0,0,1,data scientist,senior,80,132
601,Senior Data Scientist,87-141,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",Grandes Empresas,Company - Public,Research & Development,...,0,1,1,0,1,1,data scientist,senior,87,141
640,Senior Data Scientist,105-167,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",Pequeñas Grandes Empresas,Company - Private,Advertising & Marketing,...,0,0,0,0,0,0,data scientist,senior,105,167
641,Sr. ML/Data Scientist - AI/NLP/Chatbot,105-167,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",Grandes Empresas,Company - Public,Telecommunications Services,...,1,0,1,1,0,0,data scientist,senior,105,167

## e. Realiza la recodificación de la columna Size con los valores de la siguiente tabla: (hint: utilice reemplazo con diccionario usando el método replace sobre la columna.)

In [ ]:
df['Size'] = df['Size'].replace(to_replace = [
    '10000+ employees',
    '5001 to 10000 employees',
    '1001 to 5000 employees',
    '201 to 500 employees',
    '51 to 200 employees',
    '501 to 1000 employees',
    'Unknown'], value = [
    'Mega Empresas',
    'Grandes Empresas',
    'Medianas Empresas',
    'Pequeñas Empresas',
    'Pequeñas Grandes Empresas',
    'Microempresas',
    'Empresas sin Información']) #Escribimos por cuales lo cambiamos y escribimos lo que queremos cambiar.

df.head(20) #Confirmamos el cambio

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario Estimado Mínimo,Salario Estimado Máximo
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",Medianas Empresas,Nonprofit Organization,Insurance Carriers,...,0,0,0,1,0,0,data scientist,senior,137,171
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",Medianas Empresas,Company - Private,Insurance Carriers,...,0,0,0,0,0,0,data scientist,senior,75,131
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",Microempresas,Company - Private,Internet,...,1,0,0,1,1,0,data scientist,senior,75,131
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",Pequeñas Empresas,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,0,data scientist,senior,75,131
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",Pequeñas Empresas,Company - Private,Biotech & Pharmaceuticals,...,1,0,0,0,0,1,data scientist,senior,75,131
70,Principal Data Scientist,79-131,Job Requisition ID #\n20WD40121\nJob Title\nPr...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",Grandes Empresas,Company - Public,Computer Hardware & Software,...,1,1,1,1,0,1,data scientist,senior,79,131
90,Senior Data Scientist,79-131,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",Grandes Empresas,Company - Public,Research & Development,...,0,1,1,0,1,1,data scientist,senior,79,131
95,Senior Data Scientist,99-132,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",Pequeñas Grandes Empresas,Company - Private,Advertising & Marketing,...,0,0,0,0,0,0,data scientist,senior,99,132
99,Senior Data Scientist,99-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",Grandes Empresas,Company - Public,Computer Hardware & Software,...,0,1,1,0,0,1,data scientist,senior,99,132
102,Sr Data Engineer (Sr BI Developer),99-132,Description/Responsibilities\n\n\nResponsible ...,3.2,Tivity Health,"Chandler, AZ","Franklin, TN",Microempresas,Company - Public,Health Care Services & Hospitals,...,0,1,0,0,0,1,data engineer,senior,99,132
104,Lead Data Scientist,99-132,Applies advanced subject matter knowledge to s...,4.1,HP Inc.,"San Diego, CA","Palo Alto, CA",Mega Empresas,Company - Public,Computer Hardware & Software,...,1,1,0,1,0,1,data scientist,senior,99,132
117,Senior Data Engineer,99-132,About Scoop\n\nScoop brings co-workers and nei...,4.7,Scoop,"San Francisco, CA","San Francisco, CA",Pequeñas Grandes Empresas,Company - Private,Internet,...,0,0,1,0,0,0,data engineer,senior,99,132
118,Senior Data Scientist,99-132,Join our team dedicated to developing and exec...,4.5,Novetta,"Herndon, VA","Mc Lean, VA",Microempresas,Company - Private,Enterprise Software & Network Solutions,...,1,0,0,1,0,0,data scientist,senior,99,132
121,Sr. ML/Data Scientist - AI/NLP/Chatbot,99-132,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",Grandes Empresas,Company - Public,Telecommunications Services,...,1,0,1,1,0,0,data scientist,senior,99,132
125,Sr. ML/Data Scientist - AI/NLP/Chatbot,90-109,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",Grandes Empresas,Company - Public,Telecommunications Services,...,1,0,1,1,0,0,data scientist,senior,90,109
127,Senior Data Engineer,90-109,Lendio is looking to fill a position for a Sen...,4.9,Lendio,"Lehi, UT","Lehi, UT",Pequeñas Empresas,Company - Private,Lending,...,0,1,1,1,0,1,data engineer,senior,90,109
130,Senior Data Engineer,90-109,Lendio is looking to fill a position for a Sen...,4.9,Lendio,"Lehi, UT","Lehi, UT",Pequeñas Empresas,Company - Private,Lending,...,0,1,1,1,0,1,data engineer,senior,90,109
136,Senior Data Scientist,90-109,Tempo Automation is the world's fastest electr...,3.3,Tempo Automation,"San Francisco, CA","San Francisco, CA",Pequeñas Grandes Empresas,Company - Private,Electrical & Electronic Manufacturing,...,0,1,1,1,1,1,data scientist,senior,90,109
149,Sr Data Scientist,90-109,bioMérieux Inc.\n\nSr Data Scientist\n\nSENIOR...,4.2,bioMérieux,"Saint Louis, MO","Marcy-l'Etoile, France",Mega Empresas,Company - Private,Biotech & Pharmaceuticals,...,1,0,0,0,0,0,data scientist,senior,90,109
160,Senior Data Analyst,101-165,Job Requisition ID #\n20WD38079\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",Grandes Empresas,Company - Public,Computer Hardware & Software,...,0,1,1,0,0,1,analyst,senior,101,165

## f. Finalmente, genera una tabla pivote que muestre la media del salario estimado mínimo y la media del salario estimado máximo por tamaño de empresa. (hint: utiliza pd.pivot_table para generar la vista adecuada con las columnas generadas.)

tabla_pivote = pd.pivot_table(df, index = 'gender', columns = 'gender_subject', aggfunc = 'size',fill_value= 0)
tabla_pivote

In [ ]:
tabla_pivote = pd.pivot_table(df, values =['Salario Estimado Mínimo', 'Salario Estimado Máximo'], index = 'Size', aggfunc = 'mean')
tabla_pivote = tabla_pivote.sort_values(by='Salario Estimado Máximo', ascending=False) #Acomodamos para ver el salario maximo de mayor a menor
tabla_pivote

                           Salario Estimado Máximo  Salario Estimado Mínimo
Size
Mega Empresas                           151.111111                97.888889
Microempresas                           146.235294               100.176471
Pequeñas Empresas                       141.142857                93.571429
Grandes Empresas                        138.875000                92.125000
Pequeñas Grandes Empresas               137.666667               100.666667
Medianas Empresas                       137.461538                93.923077
Empresas sin Información                110.500000                73.000000