In [33]:
#Importamos pandas y numpy, generamos un menu, para visualizar las hojas que hay en el documento.
import pandas as pd
import numpy as np

menu_de_hojas = pd.ExcelFile('US_Regional_Sales_Data.xlsx').sheet_names

menu_de_hojas

['Sales Orders Sheet',
 'Customers Sheet',
 'Store Locations Sheet',
 'Products Sheet',
 'Sales Team Sheet']

In [35]:
#Se crea un dataframe con su nombre para cada hoja del documento.
df_sales = pd.read_excel('US_Regional_Sales_Data.xlsx', sheet_name ='Sales Orders Sheet')
df_customer = pd.read_excel('US_Regional_Sales_Data.xlsx', sheet_name ='Customers Sheet')
df_store = pd.read_excel('US_Regional_Sales_Data.xlsx', sheet_name ='Store Locations Sheet')
df_product = pd.read_excel('US_Regional_Sales_Data.xlsx', sheet_name ='Products Sheet')
df_team = pd.read_excel('US_Regional_Sales_Data.xlsx', sheet_name ='Sales Team Sheet')

In [47]:
#Usamos .head(2) para tener una vision del df y ver las columnas para encontrar un ID.
df_sales.head(2)

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660

In [45]:
#Usamos .head(2) para tener una vision del df y ver las columnas para encontrar un ID.
df_customer.head(2)

   _CustomerID Customer Names
0            1      Avon Corp
1            2      WakeFern

In [282]:
#Comienza el cruze de dataframes, utilizamos _CustomerID y clave left.
df_sales_customer = pd.merge(df_sales, df_customer, on ='_CustomerID', how = 'left', validate = 'many_to_one')
df_sales_customer.head(20) #Confirmamos los cambios hechos, ultima columna Customer Names.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.07,1963.10,1001.18,Rochester Ltd
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.07,3939.60,3348.66,Pacific Ltd
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.05,1775.50,781.22,"3LAB, Ltd"
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.07,2324.90,1464.69,"Fenwal, Corp"
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.10,1822.40,1476.14,Bare
5,SO - 000106,Online,WARE-PUJ1005,2017-12-31,2018-05-31,2018-06-08,2018-06-13,USD,12,21,285,1,5,0.05,1038.50,446.56,Ohio
6,SO - 000107,In-Store,WARE-XYS1001,2017-12-31,2018-05-31,2018-06-08,2018-06-14,USD,10,14,6,5,4,0.15,1192.60,536.67,Linde
7,SO - 000108,In-Store,WARE-PUJ1005,2018-04-10,2018-05-31,2018-06-26,2018-07-01,USD,6,9,280,46,5,0.05,1815.70,1525.19,Ei
8,SO - 000109,In-Store,WARE-PUJ1005,2017-12-31,2018-06-01,2018-06-16,2018-06-21,USD,4,9,299,47,4,0.30,3879.30,2211.20,Ei
9,SO - 000110,In-Store,WARE-UHY1004,2017-12-31,2018-06-01,2018-06-29,2018-07-01,USD,10,33,261,13,8,0.05,1956.40,1212.97,Trigen
10,SO - 000111,Distributor,WARE-XYS1001,2017-12-31,2018-06-01,2018-06-15,2018-06-20,USD,23,21,17,38,6,0.10,201.00,124.62,Ohio
11,SO - 000112,In-Store,WARE-NMK1003,2018-04-10,2018-06-01,2018-06-07,2018-06-17,USD,10,21,152,40,5,0.15,6277.90,2762.28,Ohio
12,SO - 000113,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-22,2018-07-02,USD,4,36,317,39,5,0.05,1051.90,641.66,O.E. Ltd
13,SO - 000114,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-07,2018-06-15,USD,8,17,291,32,6,0.15,254.60,216.41,Pure Group
14,SO - 000115,In-Store,WARE-NMK1003,2017-12-31,2018-06-01,2018-06-15,2018-06-20,USD,9,32,138,6,6,0.15,3932.90,3146.32,OHTA'S Corp
15,SO - 000116,In-Store,WARE-MKL1006,2017-12-31,2018-06-01,2018-06-24,2018-07-02,USD,5,11,354,25,3,0.05,1112.20,700.69,Apollo Ltd
16,SO - 000117,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-19,2018-06-27,USD,9,10,320,6,3,0.07,1239.50,904.83,21st Ltd
17,SO - 000118,In-Store,WARE-XYS1001,2018-04-10,2018-06-01,2018-06-06,2018-06-14,USD,8,30,21,3,4,0.10,984.90,393.96,S.S.S. Group
18,SO - 000119,In-Store,WARE-MKL1006,2018-04-10,2018-06-01,2018-06-07,2018-06-15,USD,5,5,349,20,4,0.10,5581.10,4130.01,Procter Corp
19,SO - 000120,Online,WARE-NMK1003,2017-12-31,2018-06-01,2018-06-11,2018-06-17,USD,14,23,134,24,4,0.05,3095.40,1795.33,E. Ltd

In [53]:
#Usamos .head(2) para tener una vision del df y ver las columnas para encontrar un ID.
df_store.head(2)

,_StoreID,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone
0,1,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
1,2,Huntsville,Limestone County/Madison County,AL,Alabama,City,34.69901,-86.67298,256,190582,78554,48775,552604579,3452021,America/Chicago

In [102]:
#Comienza el cruze de dataframes, utilizamos _StoreID y clave left.
df_sales_customer_store = pd.merge(df_sales_customer, df_store, on = '_StoreID', how = 'left', validate = 'many_to_one')
pd.set_option('display.max_columns', None)
df_sales_customer_store #Confirmamos los cambios, utilizamos pd.set_option para ver toda la columna, ya que pandas lo recorta.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940,Weimei Corp,San Angelo,Tom Green County,TX,Texas,City,31.46377,-100.43704,325,100450,36409,44802,155255892,5940332,America/Chicago
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560,"Apotheca, Ltd",Lafayette,Lafayette Parish,LA,Louisiana,City,30.22409,-92.01984,337,127657,50025,46517,139369271,259576,America/Chicago
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761,OHTA'S Corp,Manchester,Hillsborough County,NH,New Hampshire,City,42.99564,-71.45479,603,110229,45145,54282,85627013,4850146,America/New York
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000,Llorens Ltd,Waterbury (Town),New Haven County,CT,Connecticut,Town,41.55850,-73.03668,203,108802,40213,40467,73880017,1086045,America/New York
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820,Weimei Corp,Winston-Salem,Forsyth County,NC,North Carolina,City,36.09986,-80.24422,336,241218,93267,39882,343173025,3173027,America/New York

In [104]:
#Usamos .head(2) para tener una vision del df y ver las columnas para encontrar un ID.
df_product.head(2)

   _ProductID  Product Name
0           1      Cookware
1           2  Photo Frames

In [106]:
#Comienza el cruze de dataframes, utilizamos _ProductID y clave left.
df_sales_customer_store_product = pd.merge(df_sales_customer_store, df_product, on = '_ProductID', how = 'left', validate = 'many_to_one')
pd.set_option('display.max_columns', None)
df_sales_customer_store_product #Confirmamos los cambios, utilizamos pd.set_option para ver toda la columna, ya que pandas lo recorta.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940,Weimei Corp,San Angelo,Tom Green County,TX,Texas,City,31.46377,-100.43704,325,100450,36409,44802,155255892,5940332,America/Chicago,Pendants
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560,"Apotheca, Ltd",Lafayette,Lafayette Parish,LA,Louisiana,City,30.22409,-92.01984,337,127657,50025,46517,139369271,259576,America/Chicago,Table Lamps
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761,OHTA'S Corp,Manchester,Hillsborough County,NH,New Hampshire,City,42.99564,-71.45479,603,110229,45145,54282,85627013,4850146,America/New York,Table Linens
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000,Llorens Ltd,Waterbury (Town),New Haven County,CT,Connecticut,Town,41.55850,-73.03668,203,108802,40213,40467,73880017,1086045,America/New York,Clocks
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820,Weimei Corp,Winston-Salem,Forsyth County,NC,North Carolina,City,36.09986,-80.24422,336,241218,93267,39882,343173025,3173027,America/New York,Festive

In [108]:
#Usamos .head(2) para tener una vision del df y ver las columnas para encontrar un ID.
df_team.head(2)

   _SalesTeamID      Sales Team     Region
0             1  Adam Hernandez  Northeast
1             2   Keith Griffin  Northeast

In [110]:
#Comienza el cruze de dataframes, utilizamos _SalesTeamID y clave left.
df_sales_customer_store_product_team = pd.merge(df_sales_customer_store_product, df_team, on = '_SalesTeamID', how = 'left', validate = 'many_to_one')
pd.set_option('display.max_columns', None)
df_sales_customer_store_product_team #Confirmamos los cambios, utilizamos pd.set_option para ver toda la columna, ya que pandas lo recorta.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940,Weimei Corp,San Angelo,Tom Green County,TX,Texas,City,31.46377,-100.43704,325,100450,36409,44802,155255892,5940332,America/Chicago,Pendants,Joshua Ryan,Midwest
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560,"Apotheca, Ltd",Lafayette,Lafayette Parish,LA,Louisiana,City,30.22409,-92.01984,337,127657,50025,46517,139369271,259576,America/Chicago,Table Lamps,Paul Holmes,Midwest
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761,OHTA'S Corp,Manchester,Hillsborough County,NH,New Hampshire,City,42.99564,-71.45479,603,110229,45145,54282,85627013,4850146,America/New York,Table Linens,Paul Holmes,Midwest
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000,Llorens Ltd,Waterbury (Town),New Haven County,CT,Connecticut,Town,41.55850,-73.03668,203,108802,40213,40467,73880017,1086045,America/New York,Clocks,Anthony Torres,West
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820,Weimei Corp,Winston-Salem,Forsyth County,NC,North Carolina,City,36.09986,-80.24422,336,241218,93267,39882,343173025,3173027,America/New York,Festive,Joshua Bennett,Northeast

In [112]:
#El nombre de nuestro df actual es muy largo, vamos a simplificarlo.
df_base = df_sales_customer_store_product_team
df_base #confirmamos el cambio.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940,Weimei Corp,San Angelo,Tom Green County,TX,Texas,City,31.46377,-100.43704,325,100450,36409,44802,155255892,5940332,America/Chicago,Pendants,Joshua Ryan,Midwest
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560,"Apotheca, Ltd",Lafayette,Lafayette Parish,LA,Louisiana,City,30.22409,-92.01984,337,127657,50025,46517,139369271,259576,America/Chicago,Table Lamps,Paul Holmes,Midwest
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761,OHTA'S Corp,Manchester,Hillsborough County,NH,New Hampshire,City,42.99564,-71.45479,603,110229,45145,54282,85627013,4850146,America/New York,Table Linens,Paul Holmes,Midwest
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000,Llorens Ltd,Waterbury (Town),New Haven County,CT,Connecticut,Town,41.55850,-73.03668,203,108802,40213,40467,73880017,1086045,America/New York,Clocks,Anthony Torres,West
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820,Weimei Corp,Winston-Salem,Forsyth County,NC,North Carolina,City,36.09986,-80.24422,336,241218,93267,39882,343173025,3173027,America/New York,Festive,Joshua Bennett,Northeast

In [114]:
print(df_base.dtypes) #Aquí vemos el tipo de dato que contienen las columnas, para saber si podremos continuar tal cual.
#o bien, será necesario algun cambio.

OrderNumber                 object
Sales Channel               object
WarehouseCode               object
ProcuredDate        datetime64[ns]
OrderDate           datetime64[ns]
ShipDate            datetime64[ns]
DeliveryDate        datetime64[ns]
CurrencyCode                object
_SalesTeamID                 int64
_CustomerID                  int64
_StoreID                     int64
_ProductID                   int64
Order Quantity               int64
Discount Applied           float64
Unit Price                 float64
Unit Cost                  float64
Customer Names              object
City Name                   object
County                      object
StateCode                   object
State                       object
Type                        object
Latitude                   float64
Longitude                  float64
AreaCode                     int64
Population                   int64
Household Income             int64
Median Income                int64
Land Area                    int64
Water Area                   int64
Time Zone                   object
Product Name                object
Sales Team                  object
Region                      object
dtype: object

In [204]:
#Creamos nuevas columnas al DF con su respectiva operacion, segun el desafío.
df_base['ProcurementDays'] = df_base['OrderDate'] - df_base['ProcuredDate']
df_base['ShippingDays'] = df_base['ShipDate'] - df_base['OrderDate']
df_base['DeliveryDays'] = df_base['DeliveryDate'] - df_base['ShipDate']
df_base['CustomerDays'] = df_base['ShippingDays'] + df_base['DeliveryDays']

df_base #confirmamos los cambios.

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19 days,0 to 15 days
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest,151 days,22 days,10 days,32 days,0 to 15 days
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest,151 days,21 days,10 days,31 days,0 to 15 days
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West,151 days,2 days,5 days,7 days,NaN
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast,51 days,16 days,10 days,26 days,0 to 15 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940,Weimei Corp,San Angelo,Tom Green County,TX,Texas,City,31.46377,-100.43704,325,100450,36409,44802,155255892,5940332,America/Chicago,Pendants,Joshua Ryan,Midwest,95 days,8 days,7 days,15 days,0 to 15 days
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560,"Apotheca, Ltd",Lafayette,Lafayette Parish,LA,Louisiana,City,30.22409,-92.01984,337,127657,50025,46517,139369271,259576,America/Chicago,Table Lamps,Paul Holmes,Midwest,95 days,3 days,2 days,5 days,0 to 15 days
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761,OHTA'S Corp,Manchester,Hillsborough County,NH,New Hampshire,City,42.99564,-71.45479,603,110229,45145,54282,85627013,4850146,America/New York,Table Linens,Paul Holmes,Midwest,95 days,24 days,3 days,27 days,15 to 30 days
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000,Llorens Ltd,Waterbury (Town),New Haven County,CT,Connecticut,Town,41.55850,-73.03668,203,108802,40213,40467,73880017,1086045,America/New York,Clocks,Anthony Torres,West,95 days,21 days,5 days,26 days,15 to 30 days
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820,Weimei Corp,Winston-Salem,Forsyth County,NC,North Carolina,City,36.09986,-80.24422,336,241218,93267,39882,343173025,3173027,America/New York,Festive,Joshua Bennett,Northeast,95 days,14 days,6 days,20 days,0 to 15 days

In [206]:
print(df_base.dtypes) #confirmamos el typo de dato que tienen nuestras columnas creadas.

OrderNumber                      object
Sales Channel                    object
WarehouseCode                    object
ProcuredDate             datetime64[ns]
OrderDate                datetime64[ns]
ShipDate                 datetime64[ns]
DeliveryDate             datetime64[ns]
CurrencyCode                     object
_SalesTeamID                      int64
_CustomerID                       int64
_StoreID                          int64
_ProductID                        int64
Order Quantity                    int64
Discount Applied                float64
Unit Price                      float64
Unit Cost                       float64
Customer Names                   object
City Name                        object
County                           object
StateCode                        object
State                            object
Type                             object
Latitude                        float64
Longitude                       float64
AreaCode                          int64
Population                        int64
Household Income                  int64
Median Income                     int64
Land Area                         int64
Water Area                        int64
Time Zone                        object
Product Name                     object
Sales Team                       object
Region                           object
ProcurementDays         timedelta64[ns]
ShippingDays            timedelta64[ns]
DeliveryDays            timedelta64[ns]
CustomerDays            timedelta64[ns]
CustomerDaysInterval           category
dtype: object

In [208]:
df_base['CustomerDays'] #Visualizamos la tabla CustomerDays y vemos el tipo de dato, se encuentra en timedelta64.

0      19 days
1      32 days
2      31 days
3       7 days
4      26 days
         ...
7986   15 days
7987    5 days
7988   27 days
7989   26 days
7990   20 days
Name: CustomerDays, Length: 7991, dtype: timedelta64[ns]

In [210]:
df_base['CustomerDays'] = df_base['CustomerDays'].dt.days #Convertimos la columna a valores numericos.

In [212]:
df_base['CustomerDays'].head(5) #confirmamos el cambio

0    19
1    32
2    31
3     7
4    26
Name: CustomerDays, dtype: int64

In [290]:
#Asignamos bines y labels segun el ejercicio.
bins = [0, 15, 30 , 45, 60, 75, 90]
labels = ['0 to 15 days', '15 to 30 days', '30 to 45 days', '45 to 60 days', '60 to 75 days', '75 to 90 days']

#Creamos columna CustomerDaysInterval con la informacion de bines y labels.
df_base['CustomerDaysInterval'] = pd.cut(df_base['CustomerDays'], bins = bins, labels = labels)

In [292]:
df_base.head(20) #Confirmamos cambios

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage,CommissionsAmount,NetMargin
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.07,1963.10,1001.18,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64,-73.32,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,15 to 30 days,4073.43,0.15,611.01,3462.42
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.07,3939.60,3348.66,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98,-94.67,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest,151 days,22 days,10 days,32,30 to 45 days,886.41,0.10,88.64,797.77
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.05,1775.50,781.22,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27,-83.73,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest,151 days,21 days,10 days,31,30 to 45 days,905.50,0.10,90.55,814.95
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.07,2324.90,1464.69,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.31,-72.93,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West,151 days,2 days,5 days,7,0 to 15 days,5486.76,0.15,823.01,4663.75
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.10,1822.40,1476.14,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.56,-73.05,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast,51 days,16 days,10 days,26,15 to 30 days,1312.13,0.15,196.82,1115.31
5,SO - 000106,Online,WARE-PUJ1005,2017-12-31,2018-05-31,2018-06-08,2018-06-13,USD,12,21,285,1,5,0.05,1038.50,446.56,Ohio,Norman,Cleveland County,OK,Oklahoma,City,35.22,-97.44,405,120284,44911,51491,463011592,27576719,America/Chicago,Cookware,Carl Nguyen,Midwest,151 days,8 days,5 days,13,0 to 15 days,2700.10,0.15,405.01,2295.09
6,SO - 000107,In-Store,WARE-XYS1001,2017-12-31,2018-05-31,2018-06-08,2018-06-14,USD,10,14,6,5,4,0.15,1192.60,536.67,Linde,Chandler,Maricopa County,AZ,Arizona,City,33.31,-111.84,480,260828,88973,72695,168153308,260378,America/Phoenix,Bathroom Furniture,Jonathan Hawkins,West,151 days,8 days,6 days,14,0 to 15 days,1908.16,0.15,286.22,1621.94
7,SO - 000108,In-Store,WARE-PUJ1005,2018-04-10,2018-05-31,2018-06-26,2018-07-01,USD,6,9,280,46,5,0.05,1815.70,1525.19,Ei,Cleveland,Cuyahoga County,OH,Ohio,City,41.50,-81.70,216,388072,167100,26150,201255242,12332080,America/New York,Sculptures,Joshua Bennett,Northeast,51 days,26 days,5 days,31,30 to 45 days,998.64,0.10,99.86,898.77
8,SO - 000109,In-Store,WARE-PUJ1005,2017-12-31,2018-06-01,2018-06-16,2018-06-21,USD,4,9,299,47,4,0.30,3879.30,2211.20,Ei,North Charleston,Dorchester County/Berkeley County/Charleston C...,SC,South Carolina,City,32.92,-80.07,843,108304,37597,39543,190807625,8969264,America/New York,Audio,Chris Armstrong,Northeast,152 days,15 days,5 days,20,15 to 30 days,2017.24,0.15,302.59,1714.65
9,SO - 000110,In-Store,WARE-UHY1004,2017-12-31,2018-06-01,2018-06-29,2018-07-01,USD,10,33,261,13,8,0.05,1956.40,1212.97,Trigen,Brooklyn,Kings County,NY,New York,Borough,40.62,-73.95,347,2636735,880727,32135,180000000,70000000,America/New York,Bakeware,Jonathan Hawkins,West,152 days,28 days,2 days,30,15 to 30 days,5164.90,0.15,774.73,4390.16
10,SO - 000111,Distributor,WARE-XYS1001,2017-12-31,2018-06-01,2018-06-15,2018-06-20,USD,23,21,17,38,6,0.10,201.00,124.62,Ohio,Antioch,Contra Costa County,CA,California,City,38.00,-121.81,925,110542,33718,64329,76173197,1842711,America/Los Angeles,Wardrobes,Douglas Tucker,Midwest,152 days,14 days,5 days,19,15 to 30 days,337.68,0.10,33.77,303.91
11,SO - 000112,In-Store,WARE-NMK1003,2018-04-10,2018-06-01,2018-06-07,2018-06-17,USD,10,21,152,40,5,0.15,6277.90,2762.28,Ohio,Aurora (Township),Kane County,IL,Illinois,Township,41.77,-88.32,630,148308,44798,49797,89841331,1727843,America/Chicago,Rugs,Jonathan Hawkins,West,52 days,6 days,10 days,16,15 to 30 days,12869.69,0.20,2573.94,10295.76
12,SO - 000113,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-22,2018-07-02,USD,4,36,317,39,5,0.05,1051.90,641.66,O.E. Ltd,Denton,Denton County,TX,Texas,City,33.21,-97.13,940,131044,43745,49100,241927463,4345974,America/Chicago,Floor Lamps,Chris Armstrong,Northeast,52 days,21 days,10 days,31,30 to 45 days,1788.23,0.15,268.23,1520.00
13,SO - 000114,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-07,2018-06-15,USD,8,17,291,32,6,0.15,254.60,216.41,Pure Group,Portland,Clackamas County/Multnomah County/Washington C...,OR,Oregon,City,45.54,-122.65,503,632309,254167,55003,345657944,30147582,America/Los Angeles,Vases,George Lewis,West,52 days,6 days,8 days,14,0 to 15 days,0.00,NaN,NaN,NaN
14,SO - 000115,In-Store,WARE-NMK1003,2017-12-31,2018-06-01,2018-06-15,2018-06-20,USD,9,32,138,6,6,0.15,3932.90,3146.32,OHTA'S Corp,West Palm Beach,Palm Beach County,FL,Florida,City,26.72,-80.05,561,106779,41474,45800,142798170,6628847,America/New York,Computers,Joshua Ryan,Midwest,152 days,14 days,5 days,19,15 to 30 days,1179.87,0.15,176.98,1002.89
15,SO - 000116,In-Store,WARE-MKL1006,2017-12-31,2018-06-01,2018-06-24,2018-07-02,USD,5,11,354,25,3,0.05,1112.20,700.69,Apollo Ltd,Norfolk,Norfolk city,VA,Virginia,City,36.85,-76.29,757,246393,87045,44480,137985835,111697132,America/New York,TV and video,Stephen Payne,South,152 days,23 days,8 days,31,30 to 45 days,1067.71,0.15,160.16,907.56
16,SO - 000117,In-Store,WARE-PUJ1005,2018-04-10,2018-06-01,2018-06-19,2018-06-27,USD,9,10,320,6,3,0.07,1239.50,904.83,21st Ltd,Frisco,Collin County/Denton County,TX,Texas,City,33.16,-96.82,972,154407,45452,114098,175272056,1449212,America/Chicago,Computers,Joshua Ryan,Midwest,52 days,18 days,8 days,26,15 to 30 days,725.11,0.10,72.51,652.60
17,SO - 000118,In-Store,WARE-XYS1001,2018-04-10,2018-06-01,2018-06-06,2018-06-14,USD,8,30,21,3,4,0.10,984.90,393.96,S.S.S. Group,Carlsbad,San Diego County,CA,California,City,33.16,-117.35,760,113453,42791,90597,97713477,3595655,America/Los Angeles,Table Lamps,George Lewis,West,52 days,5 days,8 days,13,0 to 15 days,1969.80,0.15,295.47,1674.33
18,SO - 000119,In-Store,WARE-MKL1006,2018-04-10,2018-06-01,2018-06-07,2018-06-15,USD,5,5,349,20,4,0.10,5581.10,4130.01,Procter Corp,Alexandria,Alexandria city,VA,Virginia,City,38.80,-77.05,571,153511,66879,89134,38977688,1127171,America/New York,Bar Tools,Stephen Payne,South,52 days,6 days,8 days,14,0 to 15 days,3571.90,0.15,535.79,3036.12
19,SO - 000120,Online,WARE-NMK1003,2017-12-31,2018-06-01,2018-06-11,2018-06-17,USD,14,23,134,24,4,0.05,3095.40,1795.33,E. Ltd,Spring Hill,Hernando County,FL,Florida,CDP,28.48,-82.53,352,100270,39038,41308,154983928,6194314,America/New York,Wall Frames,Paul Holmes,Midwest,152 days,10 days,6 days,16,15 to 30 days,4581.19,0.15,687.18,3894.01

In [232]:
#Creamos tabla Pivote.
tabla_pivote = df_base.pivot_table(index = 'Sales Team', columns = 'CustomerDaysInterval', values = 'OrderNumber', aggfunc = 'count', fill_value = 0, observed = False)
tabla_pivote['All'] = tabla_pivote.sum(axis = 1) #Agregamos columna all para sumar las filas.
tabla_pivote.loc['All'] = tabla_pivote.sum() #Agregamos fila All al final para sumar contenido de columnas.
tabla_pivote #Mostramos la tabla.

CustomerDaysInterval,0 to 15 days,15 to 30 days,30 to 45 days,45 to 60 days,60 to 75 days,75 to 90 days,All
Sales Team,,,,,,,
Adam Hernandez,81,179,42,0,0,0,302
Anthony Berry,76,181,41,0,0,0,298
Anthony Torres,81,162,45,0,0,0,288
Carl Nguyen,96,178,40,0,0,0,314
Carlos Miller,65,148,34,0,0,0,247
Chris Armstrong,92,156,44,0,0,0,292
Donald Reynolds,97,163,36,0,0,0,296
Douglas Tucker,87,145,45,0,0,0,277
Frank Brown,85,150,40,0,0,0,275
George Lewis,104,169,42,0,0,0,315
Jerry Green,85,165,46,0,0,0,296
Joe Price,87,138,41,0,0,0,266
Jonathan Hawkins,81,143,36,0,0,0,260
Joshua Bennett,85,148,32,0,0,0,265
Joshua Little,83,165,41,0,0,0,289
Joshua Ryan,83,166,36,0,0,0,285
Keith Griffin,94,127,25,0,0,0,246
Nicholas Cunningham,88,171,34,0,0,0,293
Patrick Graham,92,130,37,0,0,0,259
Paul Holmes,61,159,41,0,0,0,261
Roger Alexander,82,147,42,0,0,0,271
Roy Rice,75,166,43,0,0,0,284
Samuel Fowler,90,162,44,0,0,0,296
Shawn Cook,88,175,40,0,0,0,303
Shawn Torres,77,160,37,0,0,0,274
Shawn Wallace,95,168,53,0,0,0,316
Stephen Payne,97,156,30,0,0,0,283
Todd Roberts,113,187,40,0,0,0,340
All,2420,4464,1107,0,0,0,7991

In [242]:
df_base['GrossMargin'] = df_base['Order Quantity'] * (df_base['Unit Price']*(1 - df_base['Discount Applied']) - df_base['Unit Cost'])

df_base.head(2)

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,15 to 30 days,4073.4325
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest,151 days,22 days,10 days,32,30 to 45 days,886.4100

In [260]:
#Asignamos bines y labels segun el ejercicio.
bins = [0, 100, 1000, 10000, 100000]
    labels = [0.05, 0.10, 0.15, 0.20]

#Creamos columna CustomerDaysInterval con la informacion de bines y labels.
df_base['CommissionsPercentage'] = pd.cut(df_base['GrossMargin'], bins = bins, labels = labels).astype(float)
df_base.head(5)

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,15 to 30 days,4073.4325,0.15
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest,151 days,22 days,10 days,32,30 to 45 days,886.4100,0.10
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest,151 days,21 days,10 days,31,30 to 45 days,905.5050,0.10
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West,151 days,2 days,5 days,7,0 to 15 days,5486.7640,0.15
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast,51 days,16 days,10 days,26,15 to 30 days,1312.1280,0.15

In [264]:
df_base['CommissionsAmount'] = df_base['GrossMargin'] * df_base['CommissionsPercentage']
df_base['NetMargin'] = df_base['GrossMargin'] - df_base['CommissionsAmount']
df_base.head(5)

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost,Customer Names,City Name,County,StateCode,State,Type,Latitude,Longitude,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage,CommissionsAmount,NetMargin
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181,Rochester Ltd,Babylon (Town),Suffolk County,NY,New York,Town,40.64092,-73.31669,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,15 to 30 days,4073.4325,0.15,611.014875,3462.417625
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660,Pacific Ltd,Overland Park,Johnson County,KS,Kansas,City,38.98223,-94.67079,913,186515,74830,72463,194562941,1309517,America/Chicago,Wreaths,Paul Holmes,Midwest,151 days,22 days,10 days,32,30 to 45 days,886.4100,0.10,88.641000,797.769000
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220,"3LAB, Ltd",Ann Arbor,Washtenaw County,MI,Michigan,City,42.27087,-83.72633,734,117070,47179,55990,72727009,2254528,America/Detroit,Stemware,Samuel Fowler,Midwest,151 days,21 days,10 days,31,30 to 45 days,905.5050,0.10,90.550500,814.954500
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687,"Fenwal, Corp",New Haven,New Haven County,CT,Connecticut,City,41.30815,-72.92816,203,130322,49771,37192,48407373,3739487,America/New York,Accessories,Carlos Miller,West,151 days,2 days,5 days,7,0 to 15 days,5486.7640,0.15,823.014600,4663.749400
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144,Bare,Waterbury,New Haven County,CT,Connecticut,City,41.55815,-73.05150,203,108802,40213,40467,73880017,1086045,America/New York,Candles,Joe Price,Northeast,51 days,16 days,10 days,26,15 to 30 days,1312.1280,0.15,196.819200,1115.308800

In [312]:
#pd.options.display.float_format = '{:.2f}'.format  # Formato con dos decimales y separadores de miles

tabla_pivote2 = df_base.pivot_table(
    index = 'Sales Team',
    values = ['GrossMargin', 'NetMargin', 'CommissionsAmount'],
    aggfunc = 'sum', fill_value = 0, observed = False)
tabla_pivote2.loc['All'] = tabla_pivote2.sum() #Agregamos fila All al final para sumar contenido de columnas.
tabla_pivote2_redondeado = tabla_pivote2.round(2)

tabla_pivote2_redondeado

                     CommissionsAmount  GrossMargin   NetMargin
Sales Team
Adam Hernandez               126637.21    779095.20   677987.33
Anthony Berry                124061.18    767943.95   654798.34
Anthony Torres               117962.21    743901.44   636758.05
Carl Nguyen                  123843.21    774781.47   661874.73
Carlos Miller                110882.09    668752.93   580326.02
Chris Armstrong              122565.71    781608.70   660857.42
Donald Reynolds              143768.34    885386.81   754038.26
Douglas Tucker               120806.40    745528.56   633786.05
Frank Brown                  104839.47    670881.25   570076.79
George Lewis                 136852.26    839150.75   710824.78
Jerry Green                  126660.44    788587.76   670379.03
Joe Price                    128822.93    787707.44   662662.11
Jonathan Hawkins             126216.94    781391.59   664629.88
Joshua Bennett               108049.11    661726.54   569242.06
Joshua Little                135806.23    840321.17   713901.23
Joshua Ryan                  114204.91    702157.82   606904.87
Keith Griffin                112940.12    675453.60   599688.29
Nicholas Cunningham          127833.00    792644.94   683164.58
Patrick Graham               121650.86    746394.00   632286.07
Paul Holmes                  114224.89    705564.60   598867.37
Roger Alexander              122487.90    773027.68   658323.84
Roy Rice                     134547.06    831446.62   706877.20
Samuel Fowler                129367.15    793254.88   671208.95
Shawn Cook                   135986.30    854878.02   724349.21
Shawn Torres                 114290.96    705619.61   600950.39
Shawn Wallace                116942.05    726737.68   624236.47
Stephen Payne                116111.48    707156.79   606241.58
Todd Roberts                 125832.14    794225.37   692123.62
All                         3444192.55  21325327.16 18227364.54